spring.application.name: gateway-server

spring:
  security:
    oauth2:
      client:
        provider:
          yelp:
            issuer-uri: http://127.0.0.1:9090
        registration:
          yelp:
            provider: yelp
            client-id: yelp
            client-secret: yelp
            authorization-grant-type:
              - authorization_code
            scope: openid, profile, email
            redirect-uri: http://127.0.0.1:8168/login/oauth2/code/yelp

  config:
    import: "configserver:"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        #        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        - SaveSession
      routes:
        - id: business # Register Business Service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/business/**
          filters:
            - TokenRelay=
            - RewritePath=/business/(?<segment>.*),/$\{segment}
        - id: identity # Register Identity Service
          uri: http://127.0.0.1:9090
          predicates:
            - Path=/identity/**
          filters:
            - TokenRelay=
            - RewritePath=/identity/(?<segment>.*),/$\{segment}
        - id: yelp-web-app # Register Frontend (NextJS)
          uri: http://127.0.0.1:3000
          predicates:
            - Path=/**

    config:
      uri: "http://localhost:8888"
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always


client-security-matchers: >
  /login/**,
  /oauth2/**,
  /logout/**,
  /en/**,
  /auth/**,
  /business/**,
  /profile/**

client-permit-matchers: >
  /login/**,
  /oauth2/**,
  /en/**,
  /auth/**,
  /contactSupport/**,
  /error/**,
  /actuator/**,
  /info/**,
  /health/**,
  /prometheus/**,
  /business/**,
  /profile/**