spring.application.name: config-server

#spring:
#  profiles:
#    active: native
#
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file:///D:/ITE Advanced/yelpMSConfig/service/{application},file:///D:/ITE Advanced/yelpMSConfig/

spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MengseuThoeng/yelp-config-server.git
          search-paths: '/service/**'
          default-label: main

server:
  port: 8888
