spring.application.name: config-server

spring:
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/ITE Advanced/yelpMSConfig/service/{application},file:///D:/ITE Advanced/yelpMSConfig/


server:
  port: 8888
